#!/bin/bash -e
# vim:ts=2:sw=2:et:
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# XXX: Generated by GitHub Copilot based on the script from v2024.08.26.00
# with modifications to create a static build.

cd "$(dirname "$0")"

set -eEux -o pipefail
PREFIX=${PREFIX:-/usr/local}

# Set CMake flags for static linking
export CMAKE_EXE_LINKER_FLAGS="-static"
export CMAKE_SHARED_LINKER_FLAGS="-static"
export CMAKE_FLAGS="-DBUILD_SHARED_LIBS=OFF -DBULID_TESTING=OFF -DBUILD_PYTHON=OFF"
export PKG_CONFIG="pkg-config --static"

python3 build/fbcode_builder/getdeps.py build \
        --allow-system-packages \
        --src-dir=. \
        "--project-install-prefix=watchman:$PREFIX" \
        watchman
python3 build/fbcode_builder/getdeps.py fixup-dyn-deps \
        --allow-system-packages \
        --src-dir=. \
        "--project-install-prefix=watchman:$PREFIX" \
        --final-install-prefix "$PREFIX" \
        watchman built

find built -ls
